#!/usr/bin/env python3
"""CoachBear dashboard server.

Dependency-free (Python 3.12 stdlib) local web app that:
  - stores and serves weekly training plans generated by the `coach-bear`
    Claude Code subagent (plans/<YYYY-Www>.md + .json sidecar metadata)
  - invokes the subagent headlessly (`claude --agent coach-bear -p ...`)
    to generate a week's plan or answer follow-up chat, as background jobs
  - parses the agent's strict plan format into structured day cards
  - stores workout logs (lifting sets, cardio sessions) and a mirror of past
    plans in SQLite (data/coachbear.db, see dashboard/db.py) and serves them
    as a training-log API with add/delete endpoints

Run:  python3 dashboard/server.py [--port 8737]
Env:  COACH_MOCK=1          use a canned plan instead of calling claude (testing)
      COACH_CLAUDE_BIN      path to the claude CLI (default: "claude")
      COACH_GEN_TIMEOUT     plan-generation timeout in seconds (default 1800)
      COACH_CHAT_TIMEOUT    chat timeout in seconds (default 900)
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import threading
import uuid
from datetime import date, datetime, timedelta
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

import db
import strava

DASH_DIR = Path(__file__).resolve().parent
ROOT = DASH_DIR.parent
STATIC_DIR = DASH_DIR / "static"
PLANS_DIR = ROOT / "plans"
MOCK_PLAN_FILE = DASH_DIR / "mock_plan.md"

MOCK = os.environ.get("COACH_MOCK") == "1"
CLAUDE_BIN = os.environ.get("COACH_CLAUDE_BIN", "claude")
GEN_TIMEOUT = int(os.environ.get("COACH_GEN_TIMEOUT", "1800"))
CHAT_TIMEOUT = int(os.environ.get("COACH_CHAT_TIMEOUT", "900"))
AGENT_NAME = "coach-bear"
# Read-only exploration + research subagents; writes only into the agent's own
# memory. Bash is limited to the training-database query wrapper (read-only)
# and the dashboard API wrapper (read/write against this server).
ALLOWED_TOOLS = (
    "Read Glob Grep Task TodoWrite WebSearch WebFetch "
    "Write(.claude/agent-memory/**) Edit(.claude/agent-memory/**) "
    "Bash(./dashboard/dbquery:*) Bash(./dashboard/api:*)"
)

# ---------------------------------------------------------------- auth policy
# Caddy forwards the authenticated basicauth username in X-Auth-User and
# overwrites any client-supplied value; an absent header means direct
# localhost access (fully trusted). Scoped users get /api/* minus the
# destructive routes below. Spec:
# docs/superpowers/specs/2026-07-13-agent-auth-hardening-design.md
FULL_ACCESS_USERS = {"", "manav"}
DESTRUCTIVE_ROUTES = (
    ("DELETE", re.compile(r".*"), "DELETE endpoints"),
    ("POST", re.compile(r"/api/plans/[^/]+/replace"), "plan replacement"),
)


def deny_reason(user: str, method: str, path: str):
    """Why this proxy user may not make this request; None if allowed."""
    if user in FULL_ACCESS_USERS:
        return None
    if not path.startswith("/api/"):
        return f"{user!r} credential may only access /api/ endpoints"
    for rule_method, rule_re, label in DESTRUCTIVE_ROUTES:
        if method == rule_method and rule_re.fullmatch(path):
            return f"{user!r} credential may not call {label}"
    return None

WEEK_KEY_RE = re.compile(r"^(\d{4})-W(\d{2})$")
DAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
DAY_HEADER_RE = re.compile(
    r"^[ \t]*(?:[#*]+[ \t]*)*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)"
    r"[ \t]*\[([^\]\n]+)\][ \t]*[*#]*[ \t]*$",
    re.MULTILINE,
)
SUMMARY_RE = re.compile(r"^[ \t]*(?:[#*]+[ \t]*)?Weekly Summary[ \t]*[*#:]*[ \t]*$", re.MULTILINE)
EXERCISE_RE = re.compile(r"^[ \t]*(\d+)[.)][ \t]+(.+?)[ \t]*$")
CARDIO_FIELD_RE = re.compile(r"^[ \t]*\**(Distance|Pace|Approx Time)\**[ \t]*:[ \t]*(.+?)[ \t]*$", re.IGNORECASE)
SPLITS_START_RE = re.compile(r"^[ \t]*\**Splits\**[ \t]*:", re.IGNORECASE)
BULLET_RE = re.compile(r"^[ \t]*[-•][ \t]*(.+?)[ \t]*$")

# ---------------------------------------------------------------- weeks

def week_key_of(d: date) -> str:
    iso = d.isocalendar()
    return f"{iso.year}-W{iso.week:02d}"


def monday_of(week_key: str) -> date:
    m = WEEK_KEY_RE.match(week_key)
    if not m:
        raise ValueError(f"bad week key: {week_key!r}")
    return date.fromisocalendar(int(m.group(1)), int(m.group(2)), 1)


def suggested_week() -> str:
    """This ISO week early in the week; from Friday on, suggest next week."""
    today = date.today()
    target = today + timedelta(days=7) if today.weekday() >= 4 else today
    return week_key_of(target)


def week_label(week_key: str) -> str:
    mon = monday_of(week_key)
    sun = mon + timedelta(days=6)
    return f"{mon:%b %d} – {sun:%b %d, %Y}"

# ---------------------------------------------------------------- plan storage

META_LOCK = threading.Lock()  # serializes read-modify-write of plan files


def plan_paths(week_key: str):
    return PLANS_DIR / f"{week_key}.md", PLANS_DIR / f"{week_key}.json"


def load_meta(week_key: str) -> dict:
    _, jpath = plan_paths(week_key)
    if jpath.exists():
        try:
            return json.loads(jpath.read_text())
        except (json.JSONDecodeError, OSError):
            pass  # corrupt sidecar: fall through to a fresh one, don't lose the .md
    return {"week": week_key, "done": {}, "chat": [], "session_id": None, "generated_at": None}


def save_meta(week_key: str, meta: dict) -> None:
    _, jpath = plan_paths(week_key)
    tmp = jpath.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(meta, indent=2))
    tmp.replace(jpath)


def save_plan(week_key: str, markdown: str, session_id, cost_usd=None) -> None:
    PLANS_DIR.mkdir(exist_ok=True)
    mpath, _ = plan_paths(week_key)
    with META_LOCK:
        meta = load_meta(week_key)
        mpath.write_text(markdown)
        meta.update(
            generated_at=datetime.now().isoformat(timespec="seconds"),
            session_id=session_id,
            cost_usd=cost_usd,
            done={},  # new plan: completion state starts over
        )
        save_meta(week_key, meta)
    mirror_plan(week_key, markdown, meta)


def mirror_plan(week_key: str, markdown: str, meta: dict) -> None:
    """Write-through copy into weekly_plans; never blocks the file save."""
    try:
        conn = db.connect()
        try:
            db.upsert_plan(conn, week_key, markdown, meta)
        finally:
            conn.close()
    except Exception as exc:
        print(f"[db] weekly_plans mirror failed for {week_key}: {exc}")


def list_plans() -> list:
    if not PLANS_DIR.is_dir():
        return []
    out = []
    for mpath in PLANS_DIR.glob("*.md"):
        week = mpath.stem
        if not WEEK_KEY_RE.match(week):
            continue
        meta = load_meta(week)
        done = meta.get("done") or {}
        out.append(
            {
                "week": week,
                "label": week_label(week),
                "generated_at": meta.get("generated_at"),
                "days_done": sum(1 for v in done.values() if v),
                "chat_count": len(meta.get("chat") or []),
            }
        )
    out.sort(key=lambda p: p["week"], reverse=True)
    return out

# ---------------------------------------------------------------- plan parsing

def classify_day(type_text: str) -> str:
    t = type_text.lower()
    if "rest" in t:
        return "rest"
    if "run" in t:
        return "run"
    if any(w in t for w in ("bike", "ride", "cycl", "spin", "zone 2")):
        return "bike"
    if any(w in t for w in ("push", "pull", "legs", "lift", "arms", "weak point")):
        return "lift"
    return "other"


def parse_day_body(kind: str, body: str) -> dict:
    """Best-effort structure; the raw lines always survive as `lines`."""
    lines = [ln.rstrip() for ln in body.strip("\n").split("\n")]
    lines = [ln for ln in lines if ln.strip()]
    out = {"lines": lines, "exercises": [], "fields": {}, "splits": []}
    in_splits = False
    for ln in lines:
        ex = EXERCISE_RE.match(ln)
        if ex:
            in_splits = False
            out["exercises"].append({"num": int(ex.group(1)), "text": ex.group(2), "warmup": None})
            continue
        stripped = ln.strip().lstrip("*").strip()
        if stripped.lower().startswith("warm-up") and out["exercises"]:
            out["exercises"][-1]["warmup"] = stripped
            continue
        field = CARDIO_FIELD_RE.match(ln)
        if field:
            in_splits = False
            out["fields"][field.group(1).title()] = field.group(2)
            continue
        if SPLITS_START_RE.match(ln):
            in_splits = True
            continue
        if in_splits:
            b = BULLET_RE.match(ln)
            if b:
                out["splits"].append(b.group(1))
                continue
            in_splits = False
    return out


def parse_plan(text: str) -> dict:
    text = text.replace("\r\n", "\n")
    sum_match = SUMMARY_RE.search(text)
    sum_start = sum_match.start() if sum_match else len(text)
    summary = text[sum_match.end():].strip() if sum_match else None

    headers = [m for m in DAY_HEADER_RE.finditer(text) if m.start() < sum_start]
    days = []
    for i, m in enumerate(headers):
        end = headers[i + 1].start() if i + 1 < len(headers) else sum_start
        day, type_text = m.group(1), m.group(2).strip()
        kind = classify_day(type_text)
        entry = {"day": day, "type": type_text, "kind": kind}
        entry.update(parse_day_body(kind, text[m.end():end]))
        days.append(entry)

    preamble = text[: headers[0].start()].strip() if headers else ""
    return {
        "days": days,
        "summary": summary,
        "preamble": preamble,
        "complete": [d["day"] for d in days] == DAY_NAMES,
    }

# ---------------------------------------------------------------- claude invocation

class ClaudeError(RuntimeError):
    pass


def run_claude(prompt: str, *, agent: str | None = None, resume: str | None = None, timeout: int) -> dict:
    """Run the claude CLI headlessly; returns {text, session_id, cost_usd}."""
    if MOCK:
        return _run_mock(prompt, resume=resume)

    cmd = [CLAUDE_BIN, "-p", "--output-format", "json", "--allowedTools", ALLOWED_TOOLS]
    if agent:
        cmd += ["--agent", agent]
    if resume:
        cmd += [f"--resume={resume}"]
    cmd.append(prompt)

    try:
        proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    except FileNotFoundError:
        raise ClaudeError(f"claude CLI not found (looked for {CLAUDE_BIN!r}); is it on PATH?")
    except subprocess.TimeoutExpired:
        raise ClaudeError(f"claude timed out after {timeout}s")

    if proc.returncode != 0:
        raise ClaudeError(
            f"claude exited {proc.returncode}: {(proc.stderr or proc.stdout or '').strip()[-2000:]}"
        )
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        raise ClaudeError(f"claude returned non-JSON output: {proc.stdout.strip()[-2000:]}")
    if data.get("is_error"):
        raise ClaudeError(f"claude reported an error: {str(data.get('result'))[:2000]}")
    text = data.get("result")
    if not text or not str(text).strip():
        raise ClaudeError("claude returned an empty result")
    return {
        "text": str(text),
        "session_id": data.get("session_id"),
        "cost_usd": data.get("total_cost_usd"),
    }


def _run_mock(prompt: str, resume=None) -> dict:
    import time

    time.sleep(1.0)  # let the UI exercise job polling
    if "Generate my complete 7-day training plan" in prompt:
        if not MOCK_PLAN_FILE.exists():
            raise ClaudeError(f"mock plan fixture missing: {MOCK_PLAN_FILE}")
        return {"text": MOCK_PLAN_FILE.read_text(), "session_id": f"mock-{uuid.uuid4().hex[:8]}", "cost_usd": 0.0}
    return {
        "text": "Mock Coach Bear: noted. (COACH_MOCK=1 — start the server without it to talk to the real agent.)",
        "session_id": resume or f"mock-{uuid.uuid4().hex[:8]}",
        "cost_usd": 0.0,
    }

# ---------------------------------------------------------------- prompts

def build_generate_prompt(week_key: str) -> str:
    mon = monday_of(week_key)
    sun = mon + timedelta(days=6)
    parts = [
        f"Generate my complete 7-day training plan for the week of Monday {mon:%B %d, %Y} "
        f"through Sunday {sun:%B %d, %Y} (ISO week {week_key})."
    ]

    prev_key = week_key_of(mon - timedelta(days=7))
    prev_md_path, _ = plan_paths(prev_key)
    prev_days = None
    prev_done = {}
    if prev_md_path.exists():
        prev_meta = load_meta(prev_key)
        prev_done = prev_meta.get("done") or {}
        if prev_done:
            marks = ", ".join(
                f"{d}: {'completed' if prev_done.get(d) else 'not marked done'}" for d in DAY_NAMES)
            parts.append(f"Last week's completion log — {marks}.")
        prev_md = prev_md_path.read_text()
        prev_days = parse_plan(prev_md)["days"]
        parts.append(
            f"Last week's plan ({prev_key}) is between the markers for progression context:\n"
            f"<last_week_plan>\n{prev_md[:8000]}\n</last_week_plan>"
        )
    else:
        parts.append("No stored plan exists for last week; treat this as the current baseline week.")

    try:
        conn = db.connect()
        try:
            digest = db.build_digest(conn, mon - timedelta(days=7), prev_days, prev_done)
        finally:
            conn.close()
        if digest:
            parts.append(
                "Training log digest (ACTUAL logged data — authoritative over plan text; use it "
                "for §5.3/§5.4 load progression, ramp cardio from actual volume per §4.3.7, and "
                "adjust for missed sessions per your adherence rules):\n"
                f"<training_digest>\n{digest}\n</training_digest>"
            )
    except Exception as exc:
        print(f"[db] digest failed: {exc}")

    parts.append(
        "Output requirements: reply with ONLY the plan in your strict output format — all 7 day "
        "sections in order Monday through Sunday, each day starting with '<Day> [<Type>]' on its own "
        "line, then the Weekly Summary. No preamble before Monday's header and no questions; state "
        "assumptions in the Weekly Summary flags instead."
    )
    return "\n\n".join(parts)


def build_chat_prompt(week_key: str, message: str, has_session: bool) -> str:
    if has_session:
        return message
    mpath, _ = plan_paths(week_key)
    plan_md = mpath.read_text()[:8000] if mpath.exists() else "(no stored plan)"
    return (
        f"Here is my current training plan for week {week_key}:\n"
        f"<plan>\n{plan_md}\n</plan>\n\n"
        f"My question/request: {message}\n\n"
        "If your answer changes the plan, emit the full revised 7-day plan in your strict output format."
    )

# ---------------------------------------------------------------- jobs

JOBS: dict = {}
JOBS_LOCK = threading.Lock()
_RUNNING: list = []  # holds at most one running job id


def start_job(kind: str, week: str, target) -> dict:
    with JOBS_LOCK:
        if _RUNNING:
            running = JOBS[_RUNNING[0]]
            return {"error": f"a {running['kind']} job for {running['week']} is already running", "job": running}
        job = {
            "id": uuid.uuid4().hex[:12],
            "kind": kind,
            "week": week,
            "status": "running",
            "started_at": datetime.now().isoformat(timespec="seconds"),
            "finished_at": None,
            "error": None,
        }
        JOBS[job["id"]] = job
        _RUNNING.append(job["id"])
        if len(JOBS) > 40:  # keep the registry bounded
            for jid in sorted(JOBS, key=lambda j: JOBS[j]["started_at"])[: len(JOBS) - 40]:
                if jid not in _RUNNING:
                    JOBS.pop(jid, None)

    def _wrap():
        try:
            result = target()
            with JOBS_LOCK:
                job.update(status="done", finished_at=datetime.now().isoformat(timespec="seconds"), **result)
        except Exception as exc:  # surfaced to the UI verbatim — never swallowed
            with JOBS_LOCK:
                job.update(
                    status="error",
                    finished_at=datetime.now().isoformat(timespec="seconds"),
                    error=str(exc),
                )
        finally:
            with JOBS_LOCK:
                if job["id"] in _RUNNING:
                    _RUNNING.remove(job["id"])

    threading.Thread(target=_wrap, daemon=True, name=f"job-{job['id']}").start()
    return {"job": job}


def generate_job(week_key: str):
    def _run():
        res = run_claude(build_generate_prompt(week_key), agent=AGENT_NAME, timeout=GEN_TIMEOUT)
        parsed = parse_plan(res["text"])
        if not parsed["days"]:
            raise ClaudeError(
                "coach-bear's reply contained no recognizable day sections; not saving. "
                f"Reply started with: {res['text'][:400]!r}"
            )
        save_plan(week_key, res["text"], res["session_id"], res.get("cost_usd"))
        return {"saved": True, "complete": parsed["complete"], "cost_usd": res.get("cost_usd")}

    return _run


def chat_job(week_key: str, message: str):
    def _run():
        with META_LOCK:
            meta = load_meta(week_key)
        session_id = meta.get("session_id")
        prompt = build_chat_prompt(week_key, message, has_session=bool(session_id))
        try:
            res = run_claude(prompt, resume=session_id, timeout=CHAT_TIMEOUT) if session_id else None
        except ClaudeError:
            res = None  # stale/unresumable session: retry below with a fresh agent session
        if res is None:
            prompt = build_chat_prompt(week_key, message, has_session=False)
            res = run_claude(prompt, agent=AGENT_NAME, timeout=CHAT_TIMEOUT)
        now = datetime.now().isoformat(timespec="seconds")
        with META_LOCK:
            meta = load_meta(week_key)
            meta.setdefault("chat", []).append({"role": "user", "text": message, "ts": now})
            meta["chat"].append({"role": "coach", "text": res["text"], "ts": now})
            meta["session_id"] = res["session_id"]
            save_meta(week_key, meta)
        return {"reply": res["text"], "cost_usd": res.get("cost_usd")}

    return _run

# ---------------------------------------------------------------- training log (SQLite)

def load_logs() -> dict:
    try:
        conn = db.connect()
        try:
            return db.fetch_log_view(conn)
        finally:
            conn.close()
    except Exception as exc:
        return {"available": False, "reason": f"database error: {exc}"}

# ---------------------------------------------------------------- HTTP handler

MIME = {".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".svg": "image/svg+xml",
        ".png": "image/png", ".ico": "image/x-icon"}
MAX_BODY = 1 << 20


class Handler(BaseHTTPRequestHandler):
    server_version = "CoachBear/1.0"

    def log_message(self, fmt, *args):  # quieter logs: only errors and API mutations
        if args and str(args[1] if len(args) > 1 else "").startswith(("4", "5")) or "POST" in (args[0] if args else ""):
            print(f"[{datetime.now():%H:%M:%S}] {fmt % args}")

    # -- helpers
    def _json(self, obj, status=200):
        body = json.dumps(obj).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _error(self, msg, status=400):
        self._json({"error": msg}, status)

    def _forbidden(self, path):
        """Enforce the proxy-user policy; True if the request was rejected."""
        reason = deny_reason(self.headers.get("X-Auth-User", ""), self.command, path)
        if reason:
            self._json({"error": reason}, 403)
            return True
        return False

    def _read_body(self):
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0 or length > MAX_BODY:
            return None
        try:
            return json.loads(self.rfile.read(length))
        except json.JSONDecodeError:
            return None

    def _redirect(self, location):
        self.send_response(302)
        self.send_header("Location", location)
        self.send_header("Content-Length", "0")
        self.end_headers()

    def _callback_uri(self):
        host = self.headers.get("Host") or "127.0.0.1:8737"
        scheme = "http" if host.split(":")[0] in ("127.0.0.1", "localhost") else "https"
        return f"{scheme}://{host}/api/strava/callback"

    def _week_or_error(self, week):
        if week and WEEK_KEY_RE.match(week):
            try:
                monday_of(week)
                return week
            except ValueError:
                pass
        self._error(f"invalid week key {week!r} (expected YYYY-Www)")
        return None

    # -- GET
    def do_GET(self):
        path = urlparse(self.path).path
        if self._forbidden(path):
            return
        try:
            if path == "/api/status":
                with JOBS_LOCK:
                    running = JOBS.get(_RUNNING[0]) if _RUNNING else None
                return self._json(
                    {
                        "plans": len(list_plans()),
                        "suggested_week": suggested_week(),
                        "current_week": week_key_of(date.today()),
                        "claude_available": MOCK or shutil.which(CLAUDE_BIN) is not None,
                        "mock": MOCK,
                        "running_job": running,
                        "agent": AGENT_NAME,
                    }
                )
            if path == "/api/plans":
                return self._json(list_plans())
            m = re.fullmatch(r"/api/plans/([^/]+)", path)
            if m:
                week = self._week_or_error(m.group(1))
                if not week:
                    return
                mpath, _ = plan_paths(week)
                if not mpath.exists():
                    return self._error(f"no plan stored for {week}", 404)
                markdown = mpath.read_text()
                meta = load_meta(week)
                return self._json(
                    {
                        "week": week,
                        "label": week_label(week),
                        "markdown": markdown,
                        "parsed": parse_plan(markdown),
                        "meta": {k: meta.get(k) for k in ("generated_at", "done", "chat", "cost_usd")},
                    }
                )
            m = re.fullmatch(r"/api/jobs/([0-9a-f]+)", path)
            if m:
                with JOBS_LOCK:
                    job = JOBS.get(m.group(1))
                return self._json(job) if job else self._error("unknown job", 404)
            if path == "/api/logs":
                return self._json(load_logs())

            if path == "/api/strava/status":
                conn = db.connect()
                try:
                    return self._json(strava.status(conn))
                finally:
                    conn.close()
            if path == "/api/strava/authorize":
                try:
                    return self._redirect(strava.authorize_url(self._callback_uri()))
                except strava.StravaError as e:
                    return self._error(str(e))
            if path == "/api/strava/callback":
                qs = parse_qs(urlparse(self.path).query)
                code = (qs.get("code") or [""])[0]
                if not code:
                    return self._error("Strava sent no authorization code"
                                       f" ({(qs.get('error') or ['denied'])[0]})")
                try:
                    strava.exchange_code(code)
                except strava.StravaError as e:
                    return self._error(str(e), 502)
                return self._redirect("/#log")

            return self._serve_static(path)
        except BrokenPipeError:
            pass
        except Exception as exc:
            self._error(f"internal error: {exc}", 500)

    # -- POST
    def do_POST(self):
        path = urlparse(self.path).path
        if self._forbidden(path):
            return
        try:
            if path == "/api/generate":
                body = self._read_body() or {}
                week = self._week_or_error(body.get("week") or suggested_week())
                if not week:
                    return
                if not MOCK and shutil.which(CLAUDE_BIN) is None:
                    return self._error("claude CLI not found on PATH", 503)
                res = start_job("generate", week, generate_job(week))
                return self._json(res, 409 if "error" in res else 202)

            if path == "/api/chat":
                body = self._read_body() or {}
                week = self._week_or_error(body.get("week"))
                if not week:
                    return
                message = (body.get("message") or "").strip()
                if not message:
                    return self._error("empty message")
                mpath, _ = plan_paths(week)
                if not mpath.exists():
                    return self._error(f"no plan stored for {week}; generate one first", 404)
                res = start_job("chat", week, chat_job(week, message))
                return self._json(res, 409 if "error" in res else 202)

            if path == "/api/strava/config":
                body = self._read_body() or {}
                try:
                    strava.set_app_config(str(body.get("client_id") or ""),
                                          str(body.get("client_secret") or ""))
                except strava.StravaError as e:
                    return self._error(str(e))
                return self._json({"ok": True, "configured": True})

            if path == "/api/strava/sync":
                conn = db.connect()
                try:
                    return self._json({"ok": True, **strava.sync(conn)})
                except strava.StravaError as e:
                    return self._error(str(e), 502)
                finally:
                    conn.close()

            if path == "/api/workouts/lift":
                body = self._read_body()
                if body is None:
                    return self._error("invalid or missing JSON body")
                try:
                    conn = db.connect()
                    try:
                        session = db.insert_lift_session(conn, body)
                    finally:
                        conn.close()
                except ValueError as ve:
                    return self._error(str(ve))
                return self._json({"ok": True, "session": session}, 201)

            if path == "/api/workouts/cardio":
                body = self._read_body()
                if body is None:
                    return self._error("invalid or missing JSON body")
                try:
                    conn = db.connect()
                    try:
                        entry = db.insert_cardio(conn, body)
                    finally:
                        conn.close()
                except ValueError as ve:
                    return self._error(str(ve))
                return self._json({"ok": True, "entry": entry}, 201)

            m = re.fullmatch(r"/api/plans/([^/]+)/done", path)
            if m:
                week = self._week_or_error(m.group(1))
                if not week:
                    return
                body = self._read_body() or {}
                day, done = body.get("day"), bool(body.get("done"))
                if day not in DAY_NAMES:
                    return self._error(f"invalid day {day!r}")
                with META_LOCK:
                    meta = load_meta(week)
                    meta.setdefault("done", {})[day] = done
                    save_meta(week, meta)
                mpath, _ = plan_paths(week)
                if mpath.exists():
                    mirror_plan(week, mpath.read_text(), meta)
                return self._json({"week": week, "done": meta["done"]})

            m = re.fullmatch(r"/api/plans/([^/]+)/replace", path)
            if m:
                week = self._week_or_error(m.group(1))
                if not week:
                    return
                body = self._read_body() or {}
                markdown = (body.get("markdown") or "").strip()
                if not markdown:
                    return self._error("empty markdown")
                parsed = parse_plan(markdown)
                if not parsed["days"]:
                    return self._error("that text has no recognizable day sections; not saving")
                PLANS_DIR.mkdir(exist_ok=True)
                mpath, _ = plan_paths(week)
                with META_LOCK:
                    meta = load_meta(week)
                    mpath.write_text(markdown)
                    meta["revised_at"] = datetime.now().isoformat(timespec="seconds")
                    save_meta(week, meta)
                mirror_plan(week, markdown, meta)
                return self._json({"week": week, "saved": True, "complete": parsed["complete"]})

            return self._error("unknown endpoint", 404)
        except BrokenPipeError:
            pass
        except Exception as exc:
            self._error(f"internal error: {exc}", 500)

    # -- DELETE
    def do_DELETE(self):
        path = urlparse(self.path).path
        if self._forbidden(path):
            return
        try:
            m = re.fullmatch(r"/api/workouts/lift/(.+)", path)
            if m:
                key = unquote(m.group(1))
                conn = db.connect()
                try:
                    n = db.delete_lift_session(conn, key)
                except ValueError as ve:
                    return self._error(str(ve))
                finally:
                    conn.close()
                if n == 0:
                    return self._error(f"no lifting session {key!r}", 404)
                return self._json({"ok": True, "deleted": n})

            m = re.fullmatch(r"/api/workouts/cardio/(\d+)", path)
            if m:
                conn = db.connect()
                try:
                    n = db.delete_cardio(conn, int(m.group(1)))
                finally:
                    conn.close()
                if n == 0:
                    return self._error("no such cardio entry", 404)
                return self._json({"ok": True, "deleted": n})

            return self._error("unknown endpoint", 404)
        except BrokenPipeError:
            pass
        except Exception as exc:
            self._error(f"internal error: {exc}", 500)

    # -- static
    def _serve_static(self, path):
        rel = "index.html" if path in ("/", "/index.html") else path.lstrip("/")
        target = (STATIC_DIR / rel).resolve()
        if not target.is_relative_to(STATIC_DIR) or not target.is_file():
            return self._error("not found", 404)
        body = target.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", MIME.get(target.suffix, "application/octet-stream"))
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(body)


def main():
    ap = argparse.ArgumentParser(description="CoachBear dashboard server")
    ap.add_argument("--port", type=int, default=8737)
    ap.add_argument("--host", default="127.0.0.1")
    args = ap.parse_args()

    PLANS_DIR.mkdir(exist_ok=True)
    server = ThreadingHTTPServer((args.host, args.port), Handler)
    mode = "MOCK mode (COACH_MOCK=1) — no real claude calls" if MOCK else f"live mode — agent '{AGENT_NAME}' via {CLAUDE_BIN}"
    print(f"CoachBear dashboard: http://{args.host}:{args.port}  [{mode}]")
    print(f"Plans directory: {PLANS_DIR}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nbye")


if __name__ == "__main__":
    main()
